### ISSUE TITLE
[CHORE] 프로젝트 초기 환경 세팅

### ISSUE THREAD

**Issue by hyun812** [hyun812/my-blog#1]
## 🚧 Description
프로젝트 초기 환경 세팅

## ✅ Todo
- [x] Next.js APP Router
- [x] eslint, prettier
- [x] husky, lint-staged
- [x] 디렉토리 구조
- [x] tailwind css config
